version:  "3"
services: 
    libdev:
        build: ./
        container_name: commonlib_dev
        stdin_open: true
        tty: true
        volumes: 
            - ../../easyscript:/commonlib
        