#!bin/bash
#    Copyright (c) 2021 on-keyday
#    Released under the MIT license
#    https://opensource.org/licenses/mit-license.php
. ../common/reconfig_common.sh
cmake -G $CMAKE_GENERATOR -D CMAKE_BUILD_TYPE=$BUILD_MODE -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -B ./built .
. ../setting/unset_setting.sh
